Todo.Web/Controllers/CategoryDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Todo.Data.Context;
using Todo.Data.Models;
using Todo.Business.Services;
using Todo.Web.ViewModels;

namespace Todo.Web.Controllers
{
    public class CategoryDBController : Controller
    {
        private readonly IDataServiceAsync<CategoryVo> provider;
        private readonly IMapper mapper;

        public CategoryDBController(IMapper mapper, IDataServiceAsync<CategoryVo> provider)
        {
            this.provider = provider;
            this.mapper = mapper;
        }

        // GET: CategoryDB
        public async Task<IActionResult> Index()
        {
            var categories = await provider.GetAll();
            return View(mapper.Map<IEnumerable<CategoryViewModel>>(categories));
        }

        // GET: CategoryDB/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await provider.Get((int)id);
            if (category == null)
            {
                return NotFound();
            }
            return View(mapper.Map<CategoryViewModel>(category));
        }

        // GET: CategoryDB/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoryDB/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] CategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                var categoryVo = mapper.Map<CategoryVo>(category);
                await provider.Add(categoryVo);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: CategoryDB/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await provider.Get((int)id);
            if (category == null)
            {
                return NotFound();
            }
            return View(mapper.Map<CategoryViewModel>(category));
        }

        // POST: CategoryDB/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] CategoryViewModel category)
        {
            if (id != category.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var categoryVo = mapper.Map<CategoryVo>(category);
                    await provider.Edit(categoryVo);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!provider.Exists(category.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: CategoryDB/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await provider.Get((int)id);
            if (category == null)
            {
                return NotFound();
            }

            return View(mapper.Map<CategoryViewModel>(category));
        }

        // POST: CategoryDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await provider.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Todo.Web/Controllers/ClientApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Todo.ApiClient;

namespace Todo.Web.Controllers
{
    public class ClientApiController : Controller
    {
        private readonly ClientsClass clientApi;

        public ClientApiController(ClientsClass clientApi)
        {
            this.clientApi = clientApi;
        }
        // GET: ClientApi
        public async Task<IActionResult> Index()
        {
            return View(await clientApi.ApiClientsGetAsync());
        }
    }
}

Todo.Web/Controllers/ProjectApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Todo.ApiClient;

namespace Todo.Web.Controllers
{
    public class ProjectApiController : Controller
    {
        private readonly ClientsClass api;

        public ProjectApiController(ClientsClass api)
        {
            this.api = api;
        }
        // GET: ProjectApi
        public async Task<IActionResult> Index()
        {
            return View(await api.ApiProjectsGetAsync());
        }
    }
}

Todo.Web/Controllers/TagDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Todo.Business.Services;
using Todo.Data.Models;
using Todo.Web.ViewModels;

namespace Todo.Web.Controllers
{
    public class TagDBController : Controller
    {
        private readonly IDataServiceAsync<TagVo> provider;
        private readonly IMapper mapper;

        public TagDBController(IMapper mapper, IDataServiceAsync<TagVo> provider)
        {
            this.provider = provider;
            this.mapper = mapper;
        }

        // GET: TagDB
        public async Task<IActionResult> Index()
        {
            var tags = await provider.GetAll();
            return View(mapper.Map<IEnumerable<TagViewModel>>(tags));
        }

        // GET: TagDB/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await provider.Get((int)id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(mapper.Map<TagViewModel>(tag));
        }

        // GET: TagDB/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TagDB/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] TagViewModel tag)
        {
            if (ModelState.IsValid)
            {
                var tagVo = mapper.Map<TagVo>(tag);
                await provider.Add(tagVo);
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: TagDB/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await provider.Get((int)id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(mapper.Map<TagViewModel>(tag));
        }

        // POST: TagDB/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] TagViewModel tag)
        {
            if (id != tag.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var tagVo = mapper.Map<TagVo>(tag);
                    await provider.Edit(tagVo);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!provider.Exists(tag.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: TagDB/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await provider.Get((int)id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(mapper.Map<TagViewModel>(tag));
        }

        // POST: TagDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await provider.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Todo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TO DO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TO DO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoItemDB" asp-action="Index">To-do items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryDB" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TagDB" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoItemTagDB" asp-action="Index">To-do-items and tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClientApi" asp-action="Index">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProjectApi" asp-action="Index">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - to-do-app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>